### ISSUE TITLE
Question running as Linux app

### ISSUE THREAD

**Issue by Fireflaker** [cnlohr/colorchord#74]
Hello.
Thank you for providing such an amazing project!
I have a question building for Linux. The colorchord2 file has been made successfully and runs well. However, the output window is transparent and shows nothing. The command prompt does not process any keyboard inputs. I am running it on a Chromebook Linux and I tried both Kali rolling LXDE and Ubuntu LXDE. Is there a requirement on what graphics system it runs on?

Thank you!

**Comment by cnlohr** [comment]
Two directions we can go with this:
1) The usual cause of issues with colorchord is the sound input device not being mapped right.  Are you sure you are getting sound in?  Is the window completely invisible?  Can you take a screenshot?
2) If the issue is indeed with the drawing system, can you try to get and build cnping?  https://github.com/cnlohr/cnping if this builds and works for you, it will be easier to proceed.

**Comment by Fireflaker** [comment]
Thank you! It's probably an issue with the sound input. I will try it out.

**Comment by Fireflaker** [comment]
Issue solved by enabling PulseAudio

pulseaudio -D

and everything worked. 
Thanks!

**Comment by cnlohr** [comment]
awesome!
